contextSource: env
ossBucketName: free4webide2
vscode:
  binaryDirectory:
  host: 127.0.0.1
  port: 9527
  dataDirectory: /webide/data
  dataOssPath: tests/vscode-server/vscode-server-data.tar.gz
workspace:
  directory: /webide/workspace
  ossPath: tests/vscode-server/workspace.tar.gz
